"""Property-based test — threshold-boundary correctness of discrepancy detection.

# Feature: avip-source-comparison, Property 2

Property 2: Discrepancy detection is correct at the threshold boundary.

*For any* aligned group and in-scope field present in more than one source, the
field is flagged **iff** the values are genuinely discrepant:

  * categorical / identifier fields — flagged iff the present source values
    differ (``check_exact``, Req 4.1, 4.5);
  * numeric fields — flagged iff at least one non-SHQ source's absolute
    deviation from the SHQ reference *exceeds* the per-field threshold. The
    boundary is strict: a deviation exactly at the threshold does NOT flag
    (``check_numeric``, Req 4.2, 4.5).

These are the pure comparison checks (no persistence / no DB), so this test
drives them directly with generated ``AlignedGroup`` inputs and asserts the
flag matches the independently-computed ground truth.

_Requirements: 4.1, 4.2, 4.5_
"""

from datetime import datetime, timezone

from hypothesis import given, settings
from hypothesis import strategies as st

from app.models.source_comparison import (
    AlignedGroup,
    AlignmentState,
    Provenance,
    SourceType,
)
from app.services.comparison import (
    NUMERIC_REFERENCE_SOURCE,
    check_exact,
    check_numeric,
)

# The two non-reference sources whose values are measured against SHQ.
_NON_REF_SOURCES = [s for s in SourceType if s is not NUMERIC_REFERENCE_SOURCE]


def _iso() -> str:
    return datetime(2024, 1, 1, tzinfo=timezone.utc).isoformat()


def _group(field: str, values_by_source: dict[SourceType, object]) -> AlignedGroup:
    """Build an aligned group carrying ``field`` for each source in the mapping.

    Each source contributes one record whose ``fields`` dict holds only the
    field under test, so ``_collect_present_values`` sees exactly the generated
    per-source values.
    """
    from app.models.source_comparison import SourceRecord

    records = [
        SourceRecord(
            id=f"rec-{src.value}",
            source=src,
            external_record_id=f"ext-{src.value}",
            part_number="PART-1",
            lot_number="LOT-1",
            fields={field: value},
            received_at=_iso(),
        )
        for src, value in values_by_source.items()
    ]
    return AlignedGroup(
        id="grp-1",
        part_number="PART-1",
        lot_number="LOT-1",
        present_sources=list(values_by_source.keys()),
        alignment_state=AlignmentState.COMPLETE,
        created_at=_iso(),
        updated_at=_iso(),
        records=records,
    )


# ── Categorical / identifier: flag iff present values differ (Req 4.1, 4.5) ──


# Small, collision-prone token set so equal and unequal pairs both occur often.
_CATEGORICAL_TOKENS = st.sampled_from(["A36", "SS304", "AL6061", "anodized", "bright"])


@settings(max_examples=50, deadline=None)
@given(
    a=_CATEGORICAL_TOKENS,
    b=_CATEGORICAL_TOKENS,
)
def test_exact_match_flags_iff_categorical_values_differ(a: str, b: str) -> None:
    """A categorical field is flagged iff the two present source values differ."""
    group = _group("material_grade", {SourceType.LAIR: a, SourceType.FAIR: b})

    result = check_exact(group, "material_grade")

    # Ground truth mirrors the check's own case-insensitive/trim normalization.
    should_flag = a.strip().casefold() != b.strip().casefold()

    assert (result is not None) == should_flag
    if result is not None:
        assert result.provenance is Provenance.EXACT
        assert result.values == {"LAIR": a, "FAIR": b}


# ── Numeric: flag iff a deviation from SHQ strictly exceeds threshold ────────


@settings(max_examples=50, deadline=None)
@given(
    shq=st.floats(min_value=-1_000.0, max_value=1_000.0, allow_nan=False, allow_infinity=False),
    dev_a=st.floats(min_value=-50.0, max_value=50.0, allow_nan=False, allow_infinity=False),
    dev_b=st.floats(min_value=-50.0, max_value=50.0, allow_nan=False, allow_infinity=False),
    threshold=st.floats(min_value=0.0, max_value=25.0, allow_nan=False, allow_infinity=False),
)
def test_numeric_flags_iff_deviation_from_shq_exceeds_threshold(
    shq: float, dev_a: float, dev_b: float, threshold: float
) -> None:
    """A numeric triple (two sources + SHQ reference) is flagged iff at least one
    source's absolute deviation from SHQ strictly exceeds the threshold.

    Deviations are generated by construction (SHQ +/- an offset) so cases land
    below, exactly at, and above the boundary. The ground-truth "exceeds" uses
    the same close-to-boundary tolerance as the implementation so
    floating-point representation error never desynchronizes the two sides.
    """
    import math

    val_a = shq + dev_a
    val_b = shq + dev_b
    group = _group(
        "diameter",
        {
            NUMERIC_REFERENCE_SOURCE: shq,
            _NON_REF_SOURCES[0]: val_a,
            _NON_REF_SOURCES[1]: val_b,
        },
    )

    result = check_numeric(group, "diameter", threshold)

    def _exceeds(dev: float) -> bool:
        if math.isclose(abs(dev), threshold, rel_tol=1e-9, abs_tol=1e-12):
            return False
        return abs(dev) > threshold

    should_flag = _exceeds(val_a - shq) or _exceeds(val_b - shq)

    assert (result is not None) == should_flag
    if result is not None:
        assert result.provenance is Provenance.NUMERIC


@settings(max_examples=50, deadline=None)
@given(
    shq=st.floats(min_value=1.0, max_value=500.0, allow_nan=False, allow_infinity=False),
    threshold=st.floats(min_value=0.01, max_value=10.0, allow_nan=False, allow_infinity=False),
)
def test_numeric_exactly_at_threshold_does_not_flag(shq: float, threshold: float) -> None:
    """A deviation exactly equal to the threshold is NOT flagged (strict boundary).

    One source sits exactly ``threshold`` above SHQ; the other sits exactly on
    SHQ. Since no deviation strictly exceeds the threshold, the field must not
    be flagged (Property 2, Req 4.5).
    """
    group = _group(
        "diameter",
        {
            NUMERIC_REFERENCE_SOURCE: shq,
            _NON_REF_SOURCES[0]: shq + threshold,
            _NON_REF_SOURCES[1]: shq,
        },
    )

    result = check_numeric(group, "diameter", threshold)

    assert result is None
