"""Certificate PDF generation service."""

from io import BytesIO
from pathlib import Path

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def generate_certificate_pdf(
    output_path: str,
    cert_id: str,
    token: str,
    part_number: str,
    revision: str,
    description: str,
    family: str,
    supplier: str,
    decision: str,
    decided_at: str,
    findings_count: int,
) -> None:
    """Generate an inspection certificate PDF."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CertTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=6,
        textColor=colors.HexColor("#156082"),
    )
    subtitle_style = ParagraphStyle(
        "CertSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.gray,
    )

    elements = []

    # Header
    elements.append(Paragraph("AI VISION INSPECTION PLATFORM", title_style))
    elements.append(Paragraph("Inspection Certificate", subtitle_style))
    elements.append(Spacer(1, 12))

    # Decision badge
    decision_color = (
        colors.HexColor("#1E8E3E")
        if decision == "PASS"
        else colors.HexColor("#C0392B")
    )
    decision_style = ParagraphStyle(
        "Decision",
        parent=styles["Heading1"],
        fontSize=28,
        textColor=decision_color,
        alignment=1,
    )
    elements.append(Paragraph(f"DECISION: {decision}", decision_style))
    elements.append(Spacer(1, 12))

    # Part info table
    part_data = [
        ["Part Number", part_number],
        ["Revision", revision],
        ["Description", description],
        ["Part Family", family],
        ["Supplier", supplier],
        ["Decision", decision],
        ["Findings", str(findings_count)],
        ["Decided At", decided_at or "N/A"],
        ["Certificate ID", cert_id[:8] + "..."],
    ]

    table = Table(part_data, colWidths=[120, 320])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f4f8")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 24))

    # QR Code
    verification_url = f"http://localhost:3000/api/v1/certificates/verify/{token}"
    qr = qrcode.make(verification_url, box_size=4, border=2)
    qr_buffer = BytesIO()
    qr.save(qr_buffer, format="PNG")
    qr_buffer.seek(0)

    qr_image = Image(qr_buffer, width=1.5 * inch, height=1.5 * inch)
    elements.append(qr_image)

    qr_note = ParagraphStyle("QRNote", parent=styles["Normal"], fontSize=8, textColor=colors.gray)
    elements.append(Paragraph("Scan QR code to verify certificate authenticity", qr_note))
    elements.append(Spacer(1, 12))

    # Footer
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.gray,
        alignment=1,
    )
    elements.append(Spacer(1, 24))
    elements.append(
        Paragraph(
            "This certificate was generated by the AI Vision Inspection Platform (AVIP). "
            "All inspection decisions are backed by image evidence and AI analysis. "
            "Certificate is immutable once issued.",
            footer_style,
        )
    )

    doc.build(elements)
